global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'aspnet_app'
    static_configs:
      - targets: ['host.docker.internal:5000']
  - job_name: 'mini-ecommerce'
    static_configs:
      - targets: ['host.docker.internal:5169']
    metrics_path: /metrics